=== Jiovanni-dump/lenovo_tb128fu_dump/system/system/etc/camera/pandora/source_front/Pandora.pipeline.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="PipelineNamespace" targetNamespace="PipelineNamespace"
  elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="pipeline">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="enable" type="bool" minOccurs="1" maxOccurs="1" />
      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="id" type="xs:unsignedInt" minOccurs="1" maxOccurs="1" />
      <xs:element ref="supported_usecase" minOccurs="1" maxOccurs="1" />
      <xs:element name="process_order" type="process_order_type" minOccurs="1" maxOccurs="1" />
      <xs:element ref="algorithms" minOccurs="1" maxOccurs="1" />
      <xs:element ref="linkages" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:simpleType name="bool">
  <xs:restriction base="xs:string">
    <xs:enumeration value="0" />
    <xs:enumeration value="1" />
  </xs:restriction>
</xs:simpleType>

<xs:element name="supported_usecase">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="usecase" type="usecase_type" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:simpleType name="usecase_type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="any" />
    <xs:enumeration value="preview" />
    <xs:enumeration value="snapshot" />
    <xs:enumeration value="video" />
    <xs:enumeration value="test" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="process_order_type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="fixed" />
    <xs:enumeration value="dynamic" />
  </xs:restriction>
</xs:simpleType>

<xs:element name="algorithms">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="algorithm" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="linkages">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="link" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!-- define algorithms -->
<xs:element name="algorithm">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="enable" type="bool" minOccurs="1" maxOccurs="1" />
      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="author" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="sequence" type="xs:unsignedInt" minOccurs="1" maxOccurs="1" />
      <xs:element name="algorithm_type" type="algorithmType" minOccurs="1" maxOccurs="1" />
      <xs:element ref="ports" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:simpleType name="algorithmType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="segment" />
    <xs:enumeration value="algorithm" />
  </xs:restriction>
</xs:simpleType>

<xs:element name="ports">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="port" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="port">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="type" type="port_type" minOccurs="1" maxOccurs="1" />
      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:simpleType name="port_type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="source" />
    <xs:enumeration value="sink" />
  </xs:restriction>
</xs:simpleType>

<!-- define linkages -->
<xs:element name="link">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="source" type="link_node" minOccurs="1" maxOccurs="1" />
      <xs:element name="sink" type="link_node" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="link_node">
  <xs:sequence>
    <xs:element name="algorithm" type="xs:string" minOccurs="1" maxOccurs="1" />
    <xs:element name="author" type="xs:string" minOccurs="1" maxOccurs="1" />
    <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
    <xs:element name="port" type="xs:string" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

</xs:schema>

=== Jiovanni-dump/lenovo_tb128fu_dump/system/system/etc/camera/pandora/source_main/Pandora.pipeline.PreviewVideo.1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<pipeline
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="PipelineNamespace"
  xsi:schemaLocation="PipelineNamespace Pandora.pipeline.xsd">

  <enable>1</enable>
  <name>any</name>
  <id>0</id>
  <supported_usecase>
    <usecase>preview</usecase>
    <usecase>video</usecase>
  </supported_usecase>
  <process_order>fixed</process_order>

  <algorithms>
    <algorithm>
      <enable>1</enable>
      <name>PortraitVirtual</name>
      <author>360ai</author>
      <version>1</version>
      <sequence>0</sequence>
      <algorithm_type>algorithm</algorithm_type>
    </algorithm>
    <algorithm>
      <enable>1</enable>
      <name>ImageRotate</name>
      <author>lenovo</author>
      <version>1</version>
      <sequence>1</sequence>
      <algorithm_type>algorithm</algorithm_type>
    </algorithm>
    <algorithm>
      <enable>1</enable>
      <name>PictureInPicture</name>
      <author>lenovo</author>
      <version>1</version>
      <sequence>5</sequence>
      <algorithm_type>algorithm</algorithm_type>
    </algorithm>
    <algorithm>
      <enable>1</enable>
      <name>facebeauty</name>
      <author>fotonation</author>
      <version>1</version>
      <sequence>6</sequence>
      <algorithm_type>algorithm</algorithm_type>
    </algorithm>
    <algorithm>
      <enable>1</enable>
      <name>autoframing</name>
      <author>morpho</author>
      <version>1</version>
      <sequence>8</sequence>
      <algorithm_type>algorithm</algorithm_type>
    </algorithm>
  </algorithms>

</pipeline>

=== Jiovanni-dump/lenovo_tb128fu_dump/system/system/etc/camera/pandora/source_main/Pandora.pipeline.Snapshot.1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<pipeline
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="PipelineNamespace"
  xsi:schemaLocation="PipelineNamespace Pandora.pipeline.xsd">

  <enable>1</enable>
  <name>any</name>
  <id>0</id>
  <supported_usecase>
    <usecase>snapshot</usecase>
  </supported_usecase>
  <process_order>fixed</process_order>

  <algorithms>
    <algorithm>
      <enable>1</enable>
      <name>DummySnapshotAlgorithm</name>
      <author>niklas</author>
      <version>1</version>
      <sequence>255</sequence>
      <algorithm_type>algorithm</algorithm_type>
    </algorithm>
    <algorithm>
      <enable>1</enable>
      <name>ImageRotate</name>
      <author>lenovo</author>
      <version>1</version>
      <sequence>1</sequence>
      <algorithm_type>algorithm</algorithm_type>
    </algorithm>
  </algorithms>

</pipeline>
